### ISSUE TITLE
About a metric in your paper.

### ISSUE THREAD

**Issue by imlixinyang** [Xiaoming-Yu/DMIT#1]
In the page.16 of your paper dmit, a lpips of real data is listed in a table, but in my opinion there is no pairs in real data, so how do you get this value.
Thank you and hoping for you reply.

**Comment by Xiaoming-Yu** [comment]
The average LPIPS distance of real data is calculated between random pairs of real images. 
We will include more details of the metrics in the final version of the paper.
Thanks.

**Comment by imlixinyang** [comment]
Thanks for your reply, so this of methods (not real data) is calced by generate pairs of the same attributes but different style code of every test image, right?

**Comment by Xiaoming-Yu** [comment]
Yes.

**Comment by imlixinyang** [comment]
Thank you, but i do think that the lpips distance of real data is somehow no need to compare for the different ways to calc them. Anyway your paper is very well-written, and your step from multi-domain to nlp-guided translation is very interesting!

**Comment by Xiaoming-Yu** [comment]
Thank you for your interest in our work.
Although the sampling pairs of the real data are different from generated images, the LPIPS distance of real data implies an “upper bound” of the diversity score (when the model generates high-quality images).
