### ISSUE TITLE
Not an issue - question on training set

### ISSUE THREAD

**Issue by johndpope** [Xiaoming-Yu/DMIT#11]
were there any attempts to train a city landscape?
Could you give any guidance on resources needed to achieve the mountain landscape ? 
is it 8 x GPUs v100 for a week or two?

**Comment by cyq373** [comment]
@johndpope I'm sorry to tell you that we haven't trained our model on the dataset of city landscape yet. 
For training time, we train our season transfer model at 256*256 on a single v100 in less than a week.

**Comment by johndpope** [comment]
thanks
