### ISSUE TITLE
Help for the code

### ISSUE THREAD

**Issue by LearningSyn** [Xiaoming-Yu/DMIT#3]
Hello, I implemented it according to the method described in the paper, but the result is different from the one shown in the paper. Could you please share your implementation and I can find out where I misunderstood.THX！

**Comment by Xiaoming-Yu** [comment]
Sorry for the delayed reply.  Code released date -> #4

**Comment by Xiaoming-Yu** [comment]
Hi, code is available now.
The dataset configuration will be added in the next few days.
