### ISSUE TITLE
Updated code release date?

### ISSUE THREAD

**Issue by bob80333** [Xiaoming-Yu/DMIT#4]
I saw in #2 you said you were busy with another project, and it would come out sometime before November, but it is now a week into November, do you know when it might be released?

**Comment by Xiaoming-Yu** [comment]
Sorry for the delayed release. The code will be released as soon as possible (after CVPR deadline).

**Comment by Xiaoming-Yu** [comment]
Hi, code is available now.
The dataset configuration will be added in the next few days.
