### ISSUE TITLE
The mode seeking loss in your codes

### ISSUE THREAD

**Issue by HelenMao** [Xiaoming-Yu/DMIT#6]
Hi, thanks for sharing your codes.
I came across that you added something like our [mode-seeking loss ](https://github.com/HelenMao/MSGAN) in your codes, but you mentioned it neither in your Github project nor your paper. 
Could you please cite our Github project or our paper in your paper, thanks!

**Comment by Xiaoming-Yu** [comment]
Hi, Dr. Mao, thanks for your suggestion.
I think you are talking about the diversity regulazation in [line](https://github.com/Xiaoming-Yu/DMIT/blob/master/options/train_options.py#L28).
The initial idea came form [DSGAN](https://arxiv.org/abs/1901.09024)  which is similar to MSGAN and has been cited in our paper.
We will include references to MSGAN in the next update.
